// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250402202054_Initialize_Db")]
    partial class Initialize_Db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Objects.Dto.GameAttemptDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorAnswersIds")
                        .HasColumnName("error_answers")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UserRatingChange")
                        .HasColumnName("rating_change")
                        .HasColumnType("REAL");

                    b.Property<string>("WordAnswersIds")
                        .HasColumnName("answers")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameAttempts");
                });

            modelBuilder.Entity("Objects.Dto.WordDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .HasColumnName("attributes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conjugation")
                        .HasColumnName("conjugation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageType")
                        .IsRequired()
                        .HasColumnName("language_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnName("translation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .HasColumnName("word")
                        .HasColumnType("TEXT");

                    b.Property<double>("WordRating")
                        .HasColumnName("word_rating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Objects.Src.Dto.UserDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnName("is_admin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("user_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Objects.Src.Dto.UserStatisticsDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ErrorAttempts")
                        .HasColumnName("error_attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAttempt")
                        .HasColumnName("last_time_utc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalAttempts")
                        .HasColumnName("total_attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UserRating")
                        .HasColumnName("user_rating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
