// <auto-generated />
using System;
using Domain.Src;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Objects.Src.Dto.AttemptDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedTranslations")
                        .HasColumnName("expected_trasnlation")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("HistoryId")
                        .HasColumnName("history_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnName("is_correct")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalSeconds")
                        .HasColumnName("attempt_time_sec")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserTranslation")
                        .HasColumnName("user_translation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .HasColumnName("word")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Objects.Src.Dto.WordDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnName("category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageFrom")
                        .IsRequired()
                        .HasColumnName("language_from")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageTo")
                        .IsRequired()
                        .HasColumnName("language_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .HasColumnName("translation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .HasColumnName("word")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Objects.Src.Models.AttemptHistoryDto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnName("category")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("CorrectAttempts")
                        .HasColumnName("correct_answers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("created_utc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalAttempts")
                        .HasColumnName("total_attempts")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalSeconds")
                        .HasColumnName("attempt_time_sec")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("updated_utc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordTypes")
                        .IsRequired()
                        .HasColumnName("words_types")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AttemptHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
