//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class UsersClient {
  private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
    this.http = http ? http : window as any;
    this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://localhost:8080";
  }

  registerUser(): Promise<FileResponse> {
    let url_ = this.baseUrl + "/api/users";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "POST",
      headers: {
        "Accept": "application/octet-stream"
      }
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processRegisterUser(_response);
    });
  }

  protected processRegisterUser(response: Response): Promise<FileResponse> {
    const status = response.status;
    let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
      let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
      let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
      if (fileName) {
        fileName = decodeURIComponent(fileName);
      } else {
        fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
        fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
      }
      return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<FileResponse>(null as any);
  }
}

export class WordsClient {
  private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
    this.http = http ? http : window as any;
    this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://localhost:8080";
  }

  get(from: Language | undefined, to: Language | undefined, type: WordsType | undefined): Promise<WordsViewModel> {
    let url_ = this.baseUrl + "/api/words?";
    if (from === null)
      throw new Error("The parameter 'from' cannot be null.");
    else if (from !== undefined)
      url_ += "from=" + encodeURIComponent("" + from) + "&";
    if (to === null)
      throw new Error("The parameter 'to' cannot be null.");
    else if (to !== undefined)
      url_ += "to=" + encodeURIComponent("" + to) + "&";
    if (type === null)
      throw new Error("The parameter 'type' cannot be null.");
    else if (type !== undefined)
      url_ += "type=" + encodeURIComponent("" + type) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json"
      }
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGet(_response);
    });
  }

  protected processGet(response: Response): Promise<WordsViewModel> {
    const status = response.status;
    let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = WordsViewModel.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<WordsViewModel>(null as any);
  }

  getRandom(from: Language | undefined, to: Language | undefined, type: WordsType | undefined): Promise<FileResponse> {
    let url_ = this.baseUrl + "/api/words/random?";
    if (from === null)
      throw new Error("The parameter 'from' cannot be null.");
    else if (from !== undefined)
      url_ += "from=" + encodeURIComponent("" + from) + "&";
    if (to === null)
      throw new Error("The parameter 'to' cannot be null.");
    else if (to !== undefined)
      url_ += "to=" + encodeURIComponent("" + to) + "&";
    if (type === null)
      throw new Error("The parameter 'type' cannot be null.");
    else if (type !== undefined)
      url_ += "type=" + encodeURIComponent("" + type) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/octet-stream"
      }
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetRandom(_response);
    });
  }

  protected processGetRandom(response: Response): Promise<FileResponse> {
    const status = response.status;
    let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
      let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
      let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
      if (fileName) {
        fileName = decodeURIComponent(fileName);
      } else {
        fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
        fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
      }
      return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<FileResponse>(null as any);
  }

  check(request: CheckWordRequestModel): Promise<FileResponse> {
    let url_ = this.baseUrl + "/api/words/check";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(request);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/octet-stream"
      }
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processCheck(_response);
    });
  }

  protected processCheck(response: Response): Promise<FileResponse> {
    const status = response.status;
    let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
    if (status === 200 || status === 206) {
      const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
      let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
      let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
      if (fileName) {
        fileName = decodeURIComponent(fileName);
      } else {
        fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
        fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
      }
      return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<FileResponse>(null as any);
  }
}

export class WordsViewModel implements IWordsViewModel {
  words?: { [key: string]: string; } | undefined;
  from?: Language;
  to?: Language;
  type?: WordsType;

  constructor(data?: IWordsViewModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      if (_data["words"]) {
        this.words = {} as any;
        for (let key in _data["words"]) {
          if (_data["words"].hasOwnProperty(key))
            (<any>this.words)![key] = _data["words"][key];
        }
      }
      this.from = _data["from"];
      this.to = _data["to"];
      this.type = _data["type"];
    }
  }

  static fromJS(data: any): WordsViewModel {
    data = typeof data === 'object' ? data : {};
    let result = new WordsViewModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    if (this.words) {
      data["words"] = {};
      for (let key in this.words) {
        if (this.words.hasOwnProperty(key))
          (<any>data["words"])[key] = (<any>this.words)[key];
      }
    }
    data["from"] = this.from;
    data["to"] = this.to;
    data["type"] = this.type;
    return data;
  }
}

export interface IWordsViewModel {
  words?: { [key: string]: string; } | undefined;
  from?: Language;
  to?: Language;
  type?: WordsType;
}

export enum Language {
  English = "English",
  Portugues = "Portugues",
  Russian = "Russian",
}

export enum WordsType {
  All = "All",
  Questions = "Questions",
  Nouns = "Nouns",
  Verbs = "Verbs",
  Adjectives = "Adjectives",
  Prepositions = "Prepositions",
  Adverbs = "Adverbs",
}

export class CheckWordRequestModel implements ICheckWordRequestModel {
  from?: Language;
  fromValue?: string | undefined;
  to?: Language;
  toValue?: string | undefined;
  type?: WordsType;

  constructor(data?: ICheckWordRequestModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.from = _data["from"];
      this.fromValue = _data["fromValue"];
      this.to = _data["to"];
      this.toValue = _data["toValue"];
      this.type = _data["type"];
    }
  }

  static fromJS(data: any): CheckWordRequestModel {
    data = typeof data === 'object' ? data : {};
    let result = new CheckWordRequestModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    data["from"] = this.from;
    data["fromValue"] = this.fromValue;
    data["to"] = this.to;
    data["toValue"] = this.toValue;
    data["type"] = this.type;
    return data;
  }
}

export interface ICheckWordRequestModel {
  from?: Language;
  fromValue?: string | undefined;
  to?: Language;
  toValue?: string | undefined;
  type?: WordsType;
}

export interface FileResponse {
  data: Blob;
  status: number;
  fileName?: string;
  headers?: { [name: string]: any };
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any; };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
  if (result !== null && result !== undefined)
    throw result;
  else
    throw new ApiException(message, status, response, headers, null);
}
